"""add column email in users table

Revision ID: 758984c4763a
Revises: 59fbbb50ebdd
Create Date: 2018-02-05 16:18:23.688685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758984c4763a'
down_revision = '59fbbb50ebdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
